apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-devops-java
  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-devops-java
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
