apiVersion: v1
kind: Service
metadata:
  name: demo-devops-java-service
spec:
  selector:
    app: demo-devops-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
