apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-devops-java
  template:
    metadata:
      labels:
        app: demo-devops-java
    spec:
      containers:
        - name: demo-devops-java
          image: 394013649467.dkr.ecr.us-west-2.amazonaws.com/demo-java-ecr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

      imagePullSecrets:
            - name: regcred
